vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|13 Oct 2007 17:21:04 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|universityRENWEN\\Administrator
vti_modifiedby:SR|universityRENWEN\\Administrator
vti_timecreated:TR|13 Oct 2007 17:21:04 -0000
vti_cacheddtm:TX|13 Oct 2007 17:21:04 -0000
vti_filesize:IR|5503
vti_cachedbodystyle:SR|<BODY oncontextmenu=self.event.returnValue=false onselectstart="return false" BGCOLOR=#000000 LEFTMARGIN=0 TOPMARGIN=2 MARGINWIDTH=0 MARGINHEIGHT=0 >
vti_cachedlinkinfo:VX|Q|index.css S|*.html S|images/wj1.jpg K|UserInfo.ASP S|images/grwj.jpg
vti_cachedsvcrellinks:VX|FQUS|index.css NSUS|*.html FSUS|images/wj1.jpg FKUS|UserInfo.ASP FSUS|images/grwj.jpg
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312 HTTP-EQUIV=pragma no-cache HTTP-EQUIV=Cache-Control no-cache,\\ must-revalidate HTTP-EQUIV=expires Wed,\\ 26\\ Feb\\ 1997\\ 08:21:57\\ GMT
vti_charset:SR|gb2312
vti_backlinkinfo:VX|UserInfo.ASP
