vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|13 Oct 2007 17:21:04 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|universityRENWEN\\Administrator
vti_modifiedby:SR|universityRENWEN\\Administrator
vti_timecreated:TR|13 Oct 2007 17:21:04 -0000
vti_cacheddtm:TX|13 Oct 2007 17:21:04 -0000
vti_filesize:IR|7939
vti_cachedbodystyle:SR|<body <%=Body_Label%> onmousemove='HideMenu()'>
vti_cachedlinkinfo:VX|S|cul.files/ss_1.gif S|cul.files/ss_3.gif S|cul.files/ss1_8.gif S|cul.files/ss1_3.gif S|cul.files/ss1_9.gif S|images/fcbg1.gif S|images/fcbg2.gif S|images/fcbg1.gif S|images/fcbg2.gif S|images/fcbg2.gif S|images/fcbg2.gif S|images/fcbg1.gif S|images/fcbg1.gif S|cul.files/xia1.gif
vti_cachedsvcrellinks:VX|NSUS|cul.files/ss_1.gif NSUS|cul.files/ss_3.gif NSUS|cul.files/ss1_8.gif NSUS|cul.files/ss1_3.gif NSUS|cul.files/ss1_9.gif FSUS|images/fcbg1.gif FSUS|images/fcbg2.gif FSUS|images/fcbg1.gif FSUS|images/fcbg2.gif FSUS|images/fcbg2.gif FSUS|images/fcbg2.gif FSUS|images/fcbg1.gif FSUS|images/fcbg1.gif NSUS|cul.files/xia1.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_charset:SR|gb2312
vti_backlinkinfo:VX|
