vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|13 Oct 2007 17:21:04 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|universityRENWEN\\Administrator
vti_modifiedby:SR|universityRENWEN\\Administrator
vti_timecreated:TR|13 Oct 2007 17:21:04 -0000
vti_cacheddtm:TX|13 Oct 2007 17:21:04 -0000
vti_filesize:IR|2590
vti_cachedbodystyle:SR|<body leftmargin="2" topmargin="0" marginwidth="0" marginheight="0" oncontextmenu="return false" ondragstart="return false" onselectstart ="return false" onselect="document.selection.empty()" oncopy="document.selection.empty()" onbeforecopy="return false" onmouseup="document.selection.empty()">
vti_cachedlinkinfo:VX|Q|STYLE.CSS S|* S|Images/ARROW2.GIF H|javascript:window.print() S|Images/printpage.gif H|javascript:window.print() S|images/bj4.gif
vti_cachedsvcrellinks:VX|FQUS|STYLE.CSS NSUS|* FSUS|Images/ARROW2.GIF SHUS|javascript:window.print() FSUS|Images/printpage.gif SHUS|javascript:window.print() NSUS|images/bj4.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_charset:SR|gb2312
vti_backlinkinfo:VX|Article_Show2.asp Article_Show.asp
