vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|13 Oct 2007 17:21:04 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|universityRENWEN\\Administrator
vti_modifiedby:SR|universityRENWEN\\Administrator
vti_timecreated:TR|13 Oct 2007 17:21:04 -0000
vti_cacheddtm:TX|13 Oct 2007 17:21:04 -0000
vti_filesize:IR|4819
vti_cachedbodystyle:SR|<body <%=Body_Label%> onmousemove='HideMenu()'>
vti_cachedlinkinfo:VX|S|images/ss_1.gif S|images/ss_3.gif S|images/ss1_8.gif S|images/ss1_3.gif S|images/ss1_9.gif S|Images/checkarticle.gif
vti_cachedsvcrellinks:VX|FSUS|images/ss_1.gif FSUS|images/ss_3.gif FSUS|images/ss1_8.gif FSUS|images/ss1_3.gif FSUS|images/ss1_9.gif FSUS|Images/checkarticle.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_charset:SR|gb2312
vti_backlinkinfo:VX|
