vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|13 Oct 2007 17:21:04 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|universityRENWEN\\Administrator
vti_modifiedby:SR|universityRENWEN\\Administrator
vti_timecreated:TR|13 Oct 2007 17:21:04 -0000
vti_cacheddtm:TX|13 Oct 2007 17:21:04 -0000
vti_filesize:IR|9034
vti_cachedbodystyle:SR|<body <%=Body_Label%> onmousemove='HideMenu()'>
vti_cachedlinkinfo:VX|S|Images/left01.gif S|Images/left12.gif S|Images/left03.gif S|Images/left02.gif S|Images/left08.gif H|Article_Class.asp S|article_js.asp S|Images/checkarticle.gif
vti_cachedsvcrellinks:VX|FSUS|Images/left01.gif FSUS|Images/left12.gif FSUS|Images/left03.gif FSUS|Images/left02.gif FSUS|Images/left08.gif FHUS|Article_Class.asp FSUS|article_js.asp FSUS|Images/checkarticle.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_charset:SR|gb2312
vti_backlinkinfo:VX|
