vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|13 Oct 2007 17:21:04 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|universityRENWEN\\Administrator
vti_modifiedby:SR|universityRENWEN\\Administrator
vti_timecreated:TR|13 Oct 2007 17:21:04 -0000
vti_cacheddtm:TX|13 Oct 2007 17:21:04 -0000
vti_filesize:IR|7860
vti_cachedbodystyle:SR|<body <%=Body_Label%> onmousemove='HideMenu()'>
vti_cachedlinkinfo:VX|S|skin/3/tdbg_left.gif S|images/fc1.gif S|images/fc3.gif S|images/fc.gif S|images/fc2.gif S|images/fc01.gif S|images/fc3.gif S|images/fc.gif S|images/fc4.gif S|images/m_bg.gif S|images/fcbg1.gif S|images/fcbg2.gif S|images/fcbg1.gif S|images/fcbg2.gif S|images/fcbg2.gif S|images/fcbg2.gif S|images/fcbg1.gif S|images/fcbg1.gif
vti_cachedsvcrellinks:VX|FSUS|skin/3/tdbg_left.gif FSUS|images/fc1.gif FSUS|images/fc3.gif FSUS|images/fc.gif FSUS|images/fc2.gif FSUS|images/fc01.gif FSUS|images/fc3.gif FSUS|images/fc.gif FSUS|images/fc4.gif FSUS|images/m_bg.gif FSUS|images/fcbg1.gif FSUS|images/fcbg2.gif FSUS|images/fcbg1.gif FSUS|images/fcbg2.gif FSUS|images/fcbg2.gif FSUS|images/fcbg2.gif FSUS|images/fcbg1.gif FSUS|images/fcbg1.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_charset:SR|gb2312
vti_backlinkinfo:VX|Article_Class3.ASP
